#If you choose optimizationChoice in vehicleParams yaml file as process noise, then opt_dim is 3. If you choose observation noise
#then opt_dim is 4. If you choose all, then it is 7. Lower bound should be bigger than zero because they are treat as the square of the noise.
opt_dim: 6 #dimension of the parameters that need to be optimized. must be at least 1 dimension of course
lower_bound: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01] #default for 3d process noise[0.000001, 0.000001, 0.000001] #lower bound, first one will be input as lowerbound(0), the second lowerbound(1).... dimension needs equal to opt_dim apparently
upper_bound: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]  #[1.0, 1.0, 1.0]

#step
epsilon: 0.001
#learning rate
sigma: 0.01
#iteration num
n_iterations: 80